name: Release

on: [release]

jobs:
  release:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Use Node.js 16.x
        with:
          node-version: "16"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - name: 💅🏼 Lint
        run: yarn lint

      - name: 🔨 Package
        run: yarn vsce package

      - name: Upload assets to release
        uses: Shopify/upload-to-release@master
        with:
          name: vscode-shopify-ruby.vsix
          path: vscode-shopify-ruby.vsix
          repo-token: ${{secrets.GITHUB_TOKEN }}
